# Generated by Django 5.0.6 on 2024-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Preparation', 'In Preparation'), ('Ready', 'Ready'), ('Served', 'Served'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
