# Generated by Django 5.0.6 on 2024-07-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_menuitem_available_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
