# Generated by Django 5.0.6 on 2024-07-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_menuitem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='menu_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='management.menuitem'),
        ),
    ]
