# Generated by Django 5.0.6 on 2024-07-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_inventory_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='menu_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='management.menuitem'),
        ),
    ]
